name: Keepalive
on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号自动执行
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
